add_newline = false

scan_timeout = 1000
command_timeout = 3000

[bun]
symbol = "bun "

[directory]
truncate_to_repo = false

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[lua]
symbol = "󰢱 "
style = "purple bold"

[memory_usage]
symbol = " "

[nodejs]
symbol = "󰎙 "
detect_files = ['package-lock.json', 'pnpm-lock.yaml']
detect_folders = []
detect_extensions = []

[rust]
symbol = " "

[golang]
symbol = " "
format = "via [$symbol$version](bold blue) "

[php]
symbol = " "
